require('dotenv').config();
const fs=require('fs');const fsp=fs.promises;const path=require('path');const os=require('os');const express=require('express');
const{renderOne}=require('../src/mixer');const{scanFiles,VIDEO_EXTENSIONS,AUDIO_EXTENSIONS,availableBytes}=require('../src/media');const{pickFolder}=require('../src/folder-picker');const{pickThumbnail}=require('../src/thumbnails');const{generateMetadata}=require('../src/ai');const{uploadDirect}=require('./upload');
const APP_VERSION='1.3.0';const ROOT=__dirname;const DATA=path.join(ROOT,'data');const CONFIG_FILE=path.join(DATA,'config.json');const RUNTIME_FILE=path.join(DATA,'runtime.json');const HISTORY_FILE=path.join(DATA,'history.json');
const PORT=Number(process.env.LOCAL_AGENT_PORT||3940);let busy=false;let stopping=false;let lastError='';let remoteSnapshot=null;let scanCache={at:0,clips:0,songs:0,freeGb:0};
function defaults(){return{deviceId:`${os.hostname()}-${Math.random().toString(36).slice(2,8)}`,name:os.hostname(),serverUrl:'https://automix-youtube-ai.onrender.com',agentKey:'',enabled:true,clipDir:'',musicDir:'',outputDir:path.join(os.homedir(),'Videos','AutoMixYouTubeAI'),thumbnailDir:'',clipSeconds:5,aspect:'landscape',resolution:'1080',fit:'cover',quality:'balanced',parallelSegments:2,minFreeGb:3,keepRendered:true,songMode:'ordered',nextSongIndex:0,timezone:'Asia/Samarkand',aiProvider:'template',aiLanguage:'English',pollSeconds:15};}
async function readJson(file,fallback){try{return JSON.parse(await fsp.readFile(file,'utf8'));}catch{return fallback;}}
async function writeJson(file,value){await fsp.mkdir(DATA,{recursive:true});const tmp=`${file}.${process.pid}.tmp`;await fsp.writeFile(tmp,JSON.stringify(value,null,2));await fsp.rename(tmp,file);}
async function loadConfig(){const raw=await readJson(CONFIG_FILE,null);const cfg={...defaults(),...(raw||{})};if(!raw)await writeJson(CONFIG_FILE,cfg);return cfg;}
async function saveConfig(cfg){await writeJson(CONFIG_FILE,cfg);return cfg;}
async function api(cfg,route,options={}){const base=String(cfg.serverUrl||'').replace(/\/$/,'');if(!base)throw new Error('Render server URL kiritilmagan');if(!cfg.agentKey)throw new Error('Agent pairing key kiritilmagan');const r=await fetch(`${base}${route}`,{...options,headers:{'content-type':'application/json','x-agent-key':cfg.agentKey,...(options.headers||{})},body:options.body&&typeof options.body!=='string'?JSON.stringify(options.body):options.body,signal:AbortSignal.timeout(options.timeout||30000)});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||`Cloud HTTP ${r.status}`);return body;}
async function refreshRemote(cfg){remoteSnapshot=await api(cfg,'/worker/config');return remoteSnapshot;}
async function scanLocal(cfg,force=false){if(!force&&Date.now()-scanCache.at<30000)return scanCache;const[clips,songs]=await Promise.all([scanFiles(cfg.clipDir,VIDEO_EXTENSIONS).catch(()=>[]),scanFiles(cfg.musicDir,AUDIO_EXTENSIONS).catch(()=>[])]);let freeGb=0;try{freeGb=(await availableBytes(cfg.outputDir))/1024**3;}catch{}scanCache={at:Date.now(),clips:clips.length,songs:songs.length,freeGb:Math.round(freeGb*10)/10};return scanCache;}
async function heartbeat(cfg,status='online',currentCommandId=null){const s=await scanLocal(cfg);return api(cfg,'/worker/heartbeat',{method:'POST',body:{deviceId:cfg.deviceId,name:cfg.name,platform:`${os.platform()} ${os.release()}`,appVersion:APP_VERSION,status,currentCommandId,clips:s.clips,songs:s.songs,freeGb:s.freeGb,lastError}});}
async function report(cfg,id,patch){return api(cfg,`/worker/report/${encodeURIComponent(id)}`,{method:'POST',body:patch});}
async function appendHistory(item){const list=await readJson(HISTORY_FILE,[]);list.push(item);if(list.length>300)list.splice(0,list.length-300);await writeJson(HISTORY_FILE,list);}
async function runtime(value){if(value==null){await fsp.rm(RUNTIME_FILE,{force:true}).catch(()=>{});return;}await writeJson(RUNTIME_FILE,value);}
async function processCommand(cfg,command,recoveryState=null){if(busy)throw new Error('Agent band');busy=true;let rt=recoveryState||{command,stage:'start',outputFile:'',songName:'',metadata:null,thumbnailFile:'',startedAt:new Date().toISOString()};await runtime(rt);try{await refreshRemote(cfg);const channel=remoteSnapshot.channels.find(c=>c.channelId===command.channelId);if(!channel)throw new Error('Cloud kanal topilmadi');const settings={...cfg,timezone:remoteSnapshot.settings?.timezone||cfg.timezone,aiProvider:cfg.aiProvider||'template',aiLanguage:cfg.aiLanguage||remoteSnapshot.settings?.aiLanguage||'English'};
let mix={outputFile:rt.outputFile,songName:rt.songName};if(!rt.outputFile||!fs.existsSync(rt.outputFile)){await report(cfg,command.id,{status:'rendering',stage:'Qurilmada video tayyorlanmoqda',progress:2});const localState={settings:{nextSongIndex:Number(cfg.nextSongIndex||0)}};mix=await renderOne({settings,state:localState,log:()=>{},onProgress:(p,stage)=>report(cfg,command.id,{status:'rendering',stage:`Render: ${stage}`,progress:Math.min(60,Math.round(p*.6))}).catch(()=>{})});cfg.nextSongIndex=Number(cfg.nextSongIndex||0)+(cfg.songMode==='ordered'?1:0);await saveConfig(cfg);rt={...rt,stage:'rendered',outputFile:mix.outputFile,songName:mix.songName};await runtime(rt);}else mix.songName=rt.songName;
let metadata=rt.metadata;if(!metadata){await report(cfg,command.id,{status:'metadata',stage:'Metadata tayyorlanmoqda',progress:63,songName:mix.songName});metadata=await generateMetadata({songName:mix.songName||'Track',channel,settings});rt={...rt,stage:'metadata',metadata,songName:mix.songName};await runtime(rt);}let thumbnailFile=rt.thumbnailFile;if(!thumbnailFile){thumbnailFile=await pickThumbnail(cfg.thumbnailDir).catch(()=>null);rt={...rt,thumbnailFile:thumbnailFile||'',stage:'uploading'};await runtime(rt);}await report(cfg,command.id,{status:'uploading',stage:'Qurilmadan YouTube ga yuklanmoqda',progress:68,songName:mix.songName});const token=await api(cfg,`/worker/token/${encodeURIComponent(channel.channelId)}`);const uploaded=await uploadDirect({accessToken:token.accessToken,channel,videoFile:rt.outputFile,thumbnailFile,metadata,recovering:Boolean(recoveryState),onProgress:p=>report(cfg,command.id,{status:'uploading',stage:'YouTube upload',progress:68+Math.round(p*.31)}).catch(()=>{})});await report(cfg,command.id,{status:'done',stage:'Tayyor',progress:100,songName:mix.songName,youtubeId:uploaded.videoId,youtubeUrl:uploaded.url});await appendHistory({commandId:command.id,channelId:channel.channelId,channelTitle:channel.title,songName:mix.songName,youtubeId:uploaded.videoId,youtubeUrl:uploaded.url,outputFile:rt.outputFile,completedAt:new Date().toISOString(),recovered:Boolean(recoveryState)});if(!cfg.keepRendered&&rt.outputFile)await fsp.rm(rt.outputFile,{force:true}).catch(()=>{});await runtime(null);lastError='';}catch(error){lastError=error.message;await report(cfg,command.id,{status:'failed',stage:'Xato',error:error.message}).catch(()=>{});await appendHistory({commandId:command.id,channelTitle:command.channelTitle,status:'failed',error:error.message,failedAt:new Date().toISOString()});throw error;}finally{busy=false;}}
async function recoverIfNeeded(cfg){const rt=await readJson(RUNTIME_FILE,null);if(!rt?.command)return false;try{await heartbeat(cfg,'recovering',rt.command.id);await processCommand(cfg,rt.command,rt);return true;}catch{return true;}}
async function poll(){if(stopping)return;let cfg;try{cfg=await loadConfig();if(!cfg.enabled)return;if(!cfg.agentKey||!cfg.serverUrl)return;await heartbeat(cfg,busy?'busy':'online',null);if(busy)return;const claimed=await api(cfg,'/worker/claim',{method:'POST',body:{deviceId:cfg.deviceId}});if(claimed.command)await processCommand(cfg,claimed.command);}catch(error){lastError=error.message;}finally{if(!stopping){const sec=Math.max(5,Number(cfg?.pollSeconds||15));setTimeout(poll,sec*1000);}}}

const app=express();app.use(express.json({limit:'1mb'}));app.use(express.static(path.join(ROOT,'public')));
app.get('/api/status',async(_req,res)=>{const cfg=await loadConfig();const scan=await scanLocal(cfg);const hist=await readJson(HISTORY_FILE,[]);res.json({version:APP_VERSION,busy,lastError,config:{...cfg,agentKey:cfg.agentKey?'***set***':''},scan,remote:remoteSnapshot,history:hist.slice(-50).reverse(),runtime:await readJson(RUNTIME_FILE,null)});});
app.get('/api/config',async(_req,res)=>{const cfg=await loadConfig();res.json({...cfg,agentKey:cfg.agentKey?'':cfg.agentKey,hasAgentKey:Boolean(cfg.agentKey)});});
app.put('/api/config',async(req,res)=>{const cfg=await loadConfig();const inb=req.body||{};for(const k of ['name','serverUrl','clipDir','musicDir','outputDir','thumbnailDir','aspect','resolution','quality','fit','songMode','timezone','aiProvider','aiLanguage'])if(typeof inb[k]==='string')cfg[k]=inb[k].trim();for(const k of ['clipSeconds','parallelSegments','minFreeGb','pollSeconds'])if(Number.isFinite(Number(inb[k])))cfg[k]=Number(inb[k]);for(const k of ['enabled','keepRendered'])if(typeof inb[k]==='boolean')cfg[k]=inb[k];if(typeof inb.agentKey==='string'&&inb.agentKey.trim())cfg.agentKey=inb.agentKey.trim();await saveConfig(cfg);scanCache.at=0;res.json({ok:true});});
app.post('/api/pick-folder',async(req,res)=>{try{res.json({path:await pickFolder(req.body?.title||'Papka tanlang')});}catch(e){res.status(400).json({error:e.message});}});
app.get('/api/scan',async(_req,res)=>{try{res.json(await scanLocal(await loadConfig(),true));}catch(e){res.status(400).json({error:e.message});}});
app.post('/api/test-cloud',async(_req,res)=>{try{const cfg=await loadConfig();const r=await refreshRemote(cfg);await heartbeat(cfg,'online');res.json({ok:true,channels:r.channels.length,serverTime:r.time});}catch(e){res.status(400).json({error:e.message});}});
app.post('/api/run-once',async(req,res)=>{try{const cfg=await loadConfig();if(busy)throw new Error('Agent band');const ch=String(req.body?.channelId||'');if(!ch)throw new Error('Kanal tanlanmagan');const cmd=await api(cfg,'/worker/claim',{method:'POST',body:{deviceId:cfg.deviceId}}).catch(()=>({command:null}));if(cmd.command)throw new Error('Cloud navbatida boshqa buyruq bor. Uni agent o‘zi oladi.');throw new Error('Qo‘lda ishga tushirishni Render panelidan bosing — video shu PC da tayyorlanadi.');}catch(e){res.status(400).json({error:e.message});}});
app.listen(PORT,'127.0.0.1',async()=>{console.log(`AutoMix Local Agent: http://127.0.0.1:${PORT}`);const cfg=await loadConfig();await recoverIfNeeded(cfg);poll();});
process.on('SIGINT',()=>{stopping=true;process.exit(0);});process.on('SIGTERM',()=>{stopping=true;process.exit(0);});
