const fs=require('fs');const fsp=fs.promises;const path=require('path');const{spawn}=require('child_process');
let bundledFfmpeg='';let bundledFfprobe='';try{bundledFfmpeg=require('@ffmpeg-installer/ffmpeg').path||'';}catch{}try{bundledFfprobe=require('@ffprobe-installer/ffprobe').path||'';}catch{}
const ffmpegPath=process.env.FFMPEG_PATH||bundledFfmpeg||'ffmpeg';const ffprobePath=process.env.FFPROBE_PATH||bundledFfprobe||'ffprobe';
const VIDEO_EXTENSIONS=new Set(['.mp4','.mov','.mkv','.webm','.avi','.m4v','.mpeg','.mpg','.wmv','.flv','.3gp','.ts','.mts','.m2ts','.vob']);
const AUDIO_EXTENSIONS=new Set(['.mp3','.wav','.m4a','.aac','.flac','.ogg','.opus','.wma','.aiff','.aif','.alac']);
class AbortJobError extends Error{constructor(message='Jarayon foydalanuvchi tomonidan to‘xtatildi'){super(message);this.name='AbortJobError';}}
async function scanFiles(root,extensions){if(!root)return[];const result=[];const pending=[path.resolve(root)];while(pending.length){const directory=pending.pop();let entries;try{entries=await fsp.readdir(directory,{withFileTypes:true});}catch(error){if(directory===path.resolve(root))throw error;continue;}for(const entry of entries){const absolute=path.join(directory,entry.name);if(entry.isDirectory()){if(!entry.name.startsWith('.'))pending.push(absolute);}else if(entry.isFile()&&extensions.has(path.extname(entry.name).toLowerCase()))result.push(absolute);}}return result.sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));}
function runProcess(binary,args,options={}){const{cwd,signal,onStdout,onStderr,trackChild}=options;return new Promise((resolve,reject)=>{if(signal?.aborted)return reject(new AbortJobError());const child=spawn(binary,args,{cwd,windowsHide:true,stdio:['ignore','pipe','pipe']});trackChild?.(child);let stdout='';let stderr='';const abort=()=>{if(!child.killed)child.kill('SIGKILL');};signal?.addEventListener('abort',abort,{once:true});child.stdout.on('data',chunk=>{const text=chunk.toString();stdout+=text;onStdout?.(text);});child.stderr.on('data',chunk=>{const text=chunk.toString();stderr+=text;onStderr?.(text);});child.on('error',error=>{signal?.removeEventListener('abort',abort);reject(error);});child.on('close',(code,terminationSignal)=>{signal?.removeEventListener('abort',abort);if(signal?.aborted)return reject(new AbortJobError());if(code===0)return resolve({stdout,stderr});const details=stderr.trim().split('\n').slice(-4).join(' ');reject(new Error(details||`Media dasturi ${terminationSignal?`${terminationSignal} signali`:`${code} kodi`} bilan yakunlandi`));});});}
async function probeMedia(file,signal,trackChild){const{stdout}=await runProcess(ffprobePath,['-v','error','-show_entries','format=duration:stream=codec_type,width,height,duration','-of','json',file],{signal,trackChild});const parsed=JSON.parse(stdout);const duration=Number(parsed.format?.duration||parsed.streams?.find(item=>item.duration)?.duration||0);const video=parsed.streams?.find(item=>item.codec_type==='video');const audio=parsed.streams?.find(item=>item.codec_type==='audio');return{duration,hasVideo:Boolean(video),hasAudio:Boolean(audio),width:Number(video?.width||0),height:Number(video?.height||0)};}
function outputSize(config){const longSide=config.resolution==='720'?1280:1920;const shortSide=config.resolution==='720'?720:1080;if(config.aspect==='portrait')return{width:shortSide,height:longSide};if(config.aspect==='square')return{width:shortSide,height:shortSide};return{width:longSide,height:shortSide};}
function videoFilter(config){const{width,height}=outputSize(config);if(config.fit==='contain')return`scale=${width}:${height}:force_original_aspect_ratio=decrease,pad=${width}:${height}:(ow-iw)/2:(oh-ih)/2:color=black,setsar=1,fps=30,format=yuv420p`;return`scale=${width}:${height}:force_original_aspect_ratio=increase,crop=${width}:${height},setsar=1,fps=30,format=yuv420p`;}
function encoding(config){if(config.quality==='fast')return{preset:'ultrafast',crf:'24'};if(config.quality==='high')return{preset:'medium',crf:'18'};return{preset:'veryfast',crf:'21'};}
async function renderSegment({source,destination,startAt,seconds,sourceDuration,config,signal,trackChild}){const{preset,crf}=encoding(config);const args=['-hide_banner','-loglevel','error','-y'];if(sourceDuration<seconds+.05)args.push('-stream_loop','-1');if(startAt>.01)args.push('-ss',startAt.toFixed(3));args.push('-i',source,'-t',seconds.toFixed(3),'-vf',videoFilter(config),'-an','-c:v','libx264','-preset',preset,'-crf',crf,'-pix_fmt','yuv420p','-r','30','-g','60','-sc_threshold','0','-f','mpegts',destination);await runProcess(ffmpegPath,args,{signal,trackChild});}
function parseClock(value){const parts=String(value).trim().split(':').map(Number);if(parts.length!==3||parts.some(item=>!Number.isFinite(item)))return 0;return parts[0]*3600+parts[1]*60+parts[2];}
async function muxSegments({listFile,audioFile,outputFile,duration,signal,trackChild,onProgress}){let carry='';await runProcess(ffmpegPath,['-hide_banner','-loglevel','error','-y','-f','concat','-safe','0','-i',listFile,'-i',audioFile,'-map','0:v:0','-map','1:a:0','-c:v','copy','-c:a','aac','-b:a','192k','-t',duration.toFixed(3),'-shortest','-movflags','+faststart','-progress','pipe:1','-nostats',outputFile],{signal,trackChild,onStdout:text=>{carry+=text;const lines=carry.split(/\r?\n/);carry=lines.pop()||'';for(const line of lines)if(line.startsWith('out_time=')){const current=parseClock(line.slice('out_time='.length));onProgress?.(Math.min(1,current/duration));}}});onProgress?.(1);}
async function availableBytes(directory){try{await fsp.mkdir(directory,{recursive:true});if(typeof fsp.statfs!=='function')return Number.POSITIVE_INFINITY;const stats=await fsp.statfs(directory);return Number(stats.bavail)*Number(stats.bsize);}catch{return Number.POSITIVE_INFINITY;}}
module.exports={VIDEO_EXTENSIONS,AUDIO_EXTENSIONS,AbortJobError,scanFiles,probeMedia,renderSegment,muxSegments,outputSize,availableBytes,ffmpegPath,ffprobePath};
