const {S3Client,PutObjectCommand,GetObjectCommand,HeadObjectCommand}=require('@aws-sdk/client-s3');
const{encryptJson,decryptJson}=require('./vault');
let client=null;let lastError='';let lastBackupAt=0;
function configured(){return Boolean(process.env.R2_S3_ENDPOINT&&process.env.R2_ACCESS_KEY_ID&&process.env.R2_SECRET_ACCESS_KEY&&process.env.R2_BUCKET);}
function keyName(){return process.env.R2_AUTOMIX_KEY||'automix/recovery/state-latest.json';}
function getClient(){if(!configured())return null;if(!client)client=new S3Client({region:process.env.R2_REGION||'auto',endpoint:process.env.R2_S3_ENDPOINT,credentials:{accessKeyId:process.env.R2_ACCESS_KEY_ID,secretAccessKey:process.env.R2_SECRET_ACCESS_KEY},forcePathStyle:false});return client;}
async function bodyToString(body){if(!body)return'';if(typeof body.transformToString==='function')return body.transformToString();const chunks=[];for await(const chunk of body)chunks.push(Buffer.from(chunk));return Buffer.concat(chunks).toString('utf8');}
async function backup(state,{force=false}={}){if(!configured())return{configured:false,ok:false,skipped:true};if(!force&&Date.now()-lastBackupAt<5*60*1000)return{configured:true,ok:true,skipped:true,lastBackupAt};try{const payload=JSON.stringify({v:1,at:new Date().toISOString(),vault:encryptJson(state)});await getClient().send(new PutObjectCommand({Bucket:process.env.R2_BUCKET,Key:keyName(),Body:payload,ContentType:'application/json',CacheControl:'no-store'}));lastBackupAt=Date.now();lastError='';return{configured:true,ok:true,key:keyName(),lastBackupAt};}catch(error){lastError=error.message;return{configured:true,ok:false,error:error.message};}}
async function restore(){if(!configured())return null;try{const out=await getClient().send(new GetObjectCommand({Bucket:process.env.R2_BUCKET,Key:keyName()}));const text=await bodyToString(out.Body);const parsed=JSON.parse(text);if(!parsed?.vault)throw new Error('R2 recovery formati yaroqsiz');const state=decryptJson(parsed.vault);lastError='';return{state,at:parsed.at||null,key:keyName()};}catch(error){if(error?.name==='NoSuchKey'||error?.$metadata?.httpStatusCode===404)return null;lastError=error.message;throw error;}}
async function diagnostics(){if(!configured())return{configured:false,ok:false,lastError:''};try{await getClient().send(new HeadObjectCommand({Bucket:process.env.R2_BUCKET,Key:keyName()}));lastError='';return{configured:true,ok:true,key:keyName(),lastBackupAt};}catch(error){if(error?.name==='NotFound'||error?.name==='NoSuchKey'||error?.$metadata?.httpStatusCode===404)return{configured:true,ok:true,key:keyName(),empty:true,lastBackupAt};lastError=error.message;return{configured:true,ok:false,key:keyName(),lastError};}}
module.exports={configured,backup,restore,diagnostics};
