const crypto=require('crypto'); const path=require('path');
function shuffle(items){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=crypto.randomInt(i+1);[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
function safeName(input,fallback='video'){return String(input||fallback).normalize('NFKD').replace(/[<>:"/\\|?*\x00-\x1F]/g,'-').replace(/\s+/g,' ').trim().slice(0,120)||fallback;}
function stripExtension(file){return path.basename(file,path.extname(file));}
function buildSourceSequence(files,count){if(!files.length)return[];const result=[];let previous=null;while(result.length<count){let batch=shuffle(files);if(previous&&batch.length>1&&batch[0]===previous){const swap=batch.findIndex(x=>x!==previous);[batch[0],batch[swap]]=[batch[swap],batch[0]];}for(const file of batch){if(result.length>=count)break;if(files.length>1&&file===previous)continue;result.push(file);previous=file;}}return result;}
function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms));} function id(prefix='job'){return `${prefix}_${Date.now().toString(36)}_${crypto.randomBytes(5).toString('hex')}`;} function clamp(value,min,max,fallback){const n=Number(value);if(!Number.isFinite(n))return fallback;return Math.max(min,Math.min(max,n));} function nowIso(){return new Date().toISOString();}
function zonedParts(date=new Date(),timeZone='Asia/Samarkand'){const parts=new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(date);const get=type=>parts.find(p=>p.type===type)?.value||'';return{year:get('year'),month:get('month'),day:get('day'),hour:Number(get('hour')||0),minute:Number(get('minute')||0),second:Number(get('second')||0)};}
function dateKey(date=new Date(),timeZone='Asia/Samarkand'){const p=zonedParts(date,timeZone);return `${p.year}-${p.month}-${p.day}`;} function localClock(date=new Date(),timeZone='Asia/Samarkand'){const p=zonedParts(date,timeZone);return{hour:p.hour,minute:p.minute,second:p.second};} function localDateTimeKey(date=new Date(),timeZone='Asia/Samarkand'){const p=zonedParts(date,timeZone);return `${p.year}-${p.month}-${p.day}T${String(p.hour).padStart(2,'0')}:${String(p.minute).padStart(2,'0')}`;} function localDisplay(date=new Date(),timeZone='Asia/Samarkand'){return new Intl.DateTimeFormat('uz-UZ',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).format(date);}
module.exports={shuffle,safeName,stripExtension,buildSourceSequence,sleep,id,clamp,nowIso,dateKey,localClock,localDateTimeKey,localDisplay,zonedParts};
